[package]
name = "har"
version = "0.1.0"
edition = "2024"

[dependencies]
libhar = { version = "0.1.0", path = "libhar" }

color-eyre = "0.6.4"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
clap = { version = "4.5.38", features = ["derive", "env"] }
