[package]
name = "libhar"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"
thiserror = "2.0.12"

generic-array = "1.2.0"
crc = "3.3.0"

bytemuck = { version = "1.23.0", features = ["derive", "min_const_generics"] }
chrono = "0.4.41"
